version: "2.1"

services:
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - DRUSH_OPTIONS_URI=cms-${VIRTUAL_HOST}
    # Keep cli running idle
    command: ["tail", "-f", "/dev/null"]
    healthcheck:
      disable: true # Temporary workaround to disable container healthcheck (causes performance issues with Docker)

  web:
    extends:
        file: ${HOME}/.docksal/stacks/services.yml
        service: apache
    labels:
      - io.docksal.virtual-host=cms-${VIRTUAL_HOST}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/cms/web
      - APACHE_FCGI_HOST_PORT=php:9000
    depends_on:
      - php
    healthcheck:
      disable: true # Temporary workaround to disable container healthcheck (causes performance issues with Docker)

  php:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - DRUSH_OPTIONS_URI=cms-${VIRTUAL_HOST}
    healthcheck:
      disable: true # Temporary workaround to disable container healthcheck (causes performance issues with Docker)

  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql
    # Don't disable the healthcheck here as MySQL takes some time to start and we need the healthcheck to wait for that.
    #healthcheck:
    #  disable: true # Temporary workaround to disable container healthcheck (causes performance issues with Docker)

  preview:
    hostname: preview
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    labels:
      - io.docksal.virtual-host=preview-${VIRTUAL_HOST}
      - io.docksal.virtual-port=3000
    environment:
      # This could be used for fs polling on systems where fs events are not available (Mac with NFS volumes or Windows)
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-0}
    working_dir: /var/www/frontend
    # Optionally run in debug mode by setting PREVIEW_START_COMMAND to "npm run debug"
    command: ["bash", "-lc", "npm run develop"]
    healthcheck:
      disable: true # Temporary workaround to disable container healthcheck (causes performance issues with Docker)

  frontend:
    hostname: frontend
    image: ${WEB_IMAGE:-docksal/apache:2.4-2.3}
    volumes:
      - project_root:/var/www:ro,nocopy,cached
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/public
    healthcheck:
      disable: true # Temporary workaround to disable container healthcheck (causes performance issues with Docker)
